-- Core Sentinel: one row per document scan from document_scanner.py → _sync_to_supabase.
-- Run in Supabase SQL Editor (same project as SUPABASE_URL in your .env).
--
-- Requires: SUPABASE_URL + SUPABASE_ANON_KEY set for the desktop app.
-- Rows are inserted with the anon key; RLS policies below allow insert + dashboard read.

create table if not exists public.document_scans (
  id bigint generated by default as identity primary key,
  scanned_at text not null,
  file_name text not null,
  overall_risk text not null default 'unknown',
  risk_score integer not null default 0,
  issue_count integer not null default 0,
  pii_classes text not null default ''
);

create index if not exists document_scans_scanned_at_idx
  on public.document_scans (scanned_at desc nulls last);

create index if not exists document_scans_overall_risk_idx
  on public.document_scans (overall_risk);

alter table public.document_scans enable row level security;

drop policy if exists "document_scans_select_anon" on public.document_scans;
create policy "document_scans_select_anon"
  on public.document_scans
  for select
  to anon
  using (true);

drop policy if exists "document_scans_insert_anon" on public.document_scans;
create policy "document_scans_insert_anon"
  on public.document_scans
  for insert
  to anon
  with check (true);
