-- Core Sentinel: columns expected by ui_remediation_dialog._sync_feedback_supabase
-- and docs/ml/index.html. Run in Supabase → SQL Editor, then Settings → API →
-- Reload schema (or wait ~1 min) if PostgREST still caches old columns.
--
-- If public.feedback_corrections does not exist yet, create it:

create table if not exists public.feedback_corrections (
  id bigint generated by default as identity primary key,
  text_hash text not null,
  predicted text not null,
  correct text not null,
  source text,
  feedback_type text,
  used_for_training boolean not null default false,
  "timestamp" timestamptz,
  recorded_at timestamptz,
  -- Optional (ML dashboard / richer logs):
  pii_classes text,
  risk_score integer,
  created_at timestamptz not null default now()
);

create index if not exists feedback_corrections_text_hash_idx
  on public.feedback_corrections (text_hash);

create index if not exists feedback_corrections_recorded_at_idx
  on public.feedback_corrections (recorded_at desc nulls last);

-- If the table already exists but is missing columns (PGRST204 on "predicted"):

alter table public.feedback_corrections
  add column if not exists text_hash text,
  add column if not exists predicted text,
  add column if not exists correct text,
  add column if not exists source text,
  add column if not exists feedback_type text,
  add column if not exists used_for_training boolean default false,
  add column if not exists "timestamp" timestamptz,
  add column if not exists recorded_at timestamptz,
  add column if not exists pii_classes text,
  add column if not exists risk_score integer;

-- Relax NOT NULL for backfill if you had partial legacy rows (optional):
-- alter table public.feedback_corrections alter column predicted drop not null;
-- alter table public.feedback_corrections alter column correct drop not null;

-- If RLS is enabled, grant insert/select for the anon key used by the app, e.g.:
--   alter table public.feedback_corrections enable row level security;
--   create policy "feedback_insert" on public.feedback_corrections for insert to anon with check (true);
--   create policy "feedback_select" on public.feedback_corrections for select to anon using (true);
