-- Core Sentinel: scoring events warehouse for dashboards (sync from logs/guardrail.db).
-- Run in Supabase SQL Editor after creating your project.
--
-- sentinel_sync_daemon inserts rows with SUPABASE_ANON_KEY when RLS allows INSERT for anon.

create table if not exists public.guardrail_events (
  id bigint generated by default as identity primary key,
  timestamp text not null,
  text_hash text not null,
  action text not null,
  risk_score integer not null default 0,
  pii_classes text not null default '',
  llm_name text not null default ''
);

create index if not exists guardrail_events_timestamp_idx
  on public.guardrail_events (timestamp desc nulls last);

create index if not exists guardrail_events_text_hash_idx
  on public.guardrail_events (text_hash);

-- Optional: enable RLS and allow the browser ML dashboard + hub to read with the anon key.
-- If you skip this, ensure RLS is off for this table or PostgREST will return 401/403.
alter table public.guardrail_events enable row level security;

drop policy if exists "guardrail_events_select_anon" on public.guardrail_events;
create policy "guardrail_events_select_anon"
  on public.guardrail_events
  for select
  to anon
  using (true);

-- Desktop app sync inserts with anon key (see sentinel_sync_daemon.py).
drop policy if exists "guardrail_events_insert_anon" on public.guardrail_events;
create policy "guardrail_events_insert_anon"
  on public.guardrail_events
  for insert
  to anon
  with check (true);
