-- Core Sentinel: retrain metadata sink for dashboard auto-refresh.
-- Run this in Supabase SQL Editor.
--
-- If you use a different table name, also set:
--   GUARDRAIL_RETRAIN_SUPABASE_TABLE=<your_table_name>

create table if not exists public.retrain_runs (
  id bigint generated by default as identity primary key,
  run_at timestamptz not null default now(),
  status text not null default 'success',
  model_version_tag text,
  model_path text,
  accuracy double precision,
  precision double precision,
  recall double precision,
  f1 double precision,
  recall_high double precision,
  recall_med double precision,
  feedback_rows integer,
  block_threshold double precision,
  warn_threshold double precision,
  recommended_prob_threshold_high double precision,
  recommended_prob_threshold_med double precision,
  fpr_non_high_as_high double precision,
  summary_json jsonb not null default '{}'::jsonb,
  source text not null default 'core_sentinel_auto_retrain',
  created_at timestamptz not null default now()
);

create index if not exists retrain_runs_run_at_idx
  on public.retrain_runs (run_at desc nulls last);

create index if not exists retrain_runs_created_at_idx
  on public.retrain_runs (created_at desc nulls last);

create index if not exists retrain_runs_status_idx
  on public.retrain_runs (status);

-- Optional if you use JSON queries heavily.
create index if not exists retrain_runs_summary_json_gin_idx
  on public.retrain_runs using gin (summary_json);

-- Optional RLS example for dashboard reads from anon:
-- alter table public.retrain_runs enable row level security;
-- create policy "retrain_runs_select" on public.retrain_runs
--   for select to anon using (true);
--
-- Writes from the app are best with service role key. If you must use anon for writes:
-- create policy "retrain_runs_insert" on public.retrain_runs
--   for insert to anon with check (true);
